Resources:
  Function:
    Type: AWS::Serverless::Function
    Properties:
      Timeout: 300
      MemorySize: 128
      Handler: dev.nhannht.Nice
      CodeUri: /home/fermin/nhannht-projects/xxx-stars
      Runtime: java21
      Architectures:
        - x86_64
      Environment:
        Variables:
          DOCKER_HOST: unix:///run/user/1000/podman/podman.sock